apiVersion: v1
kind: ConfigMap
metadata:
  name: eventsphere-config
  namespace: onlineeventbooking
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "devops"

  USERS_API_URL: "http://user-service:5000"
  EVENTS_API_URL: "http://event-service:5001"
  BOOKING_API_URL: "http://booking-service:5002"
  NOTIFICATIONS_API_URL: "http://notification-service:5003"

  RABBITMQ_URL: "amqp://rabbitmq"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
